# Generated by Django 5.2.14 on 2026-05-16 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnonymousUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "anonymous_users",
            },
        ),
        migrations.CreateModel(
            name="NewsCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("text", models.TextField()),
                ("source", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "label",
                    models.CharField(
                        choices=[("REAL", "Real"), ("FAKE", "Fake")], max_length=4
                    ),
                ),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="api.anonymoususer",
                    ),
                ),
            ],
            options={
                "db_table": "news_checks",
                "ordering": ["-created_at"],
            },
        ),
    ]
