# Generated by Django 5.2.14 on 2026-05-25 16:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnonymousUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "anonymous_users",
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("domain", models.CharField(max_length=200, unique=True)),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_predefined", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "news_sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("text", models.TextField()),
                (
                    "label",
                    models.CharField(
                        choices=[("REAL", "Real"), ("FAKE", "Fake")], max_length=4
                    ),
                ),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "users",
                    models.ManyToManyField(
                        db_table="news_check_users",
                        related_name="checks",
                        to="api.anonymoususer",
                    ),
                ),
                (
                    "news_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checks",
                        to="api.newssource",
                    ),
                ),
            ],
            options={
                "db_table": "news_checks",
                "ordering": ["-created_at"],
            },
        ),
    ]
