import uuid
from django.db import models


class NewsSource(models.Model):
    """
    Represents a news outlet — either one of the 47 predefined sources
    or a new one discovered at prediction time via Clearbit API.

    Predefined sources have name, domain and logo_url set from the start.
    New sources (is_predefined=False) are created with domain only;
    name and logo_url are resolved via Clearbit and filled in afterwards.
    """

    name = models.CharField(max_length=200, unique=True, null=True, blank=True)
    domain = models.CharField(max_length=200, unique=True)
    logo_url = models.URLField(max_length=500, null=True, blank=True)
    is_predefined = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "news_sources"
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.domain})"


class AnonymousUser(models.Model):
    """
    Anonymous user identified by a UUID generated in the browser.
    No registration or password required.
    The UUID is generated by the Chrome extension and stored in localStorage.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "anonymous_users"

    def __str__(self):
        return str(self.id)


class NewsCheck(models.Model):
    """
    Stores each news article analyzed by a user, along with the
    model prediction and the source it came from.
    """

    LABEL_CHOICES = [
        ("REAL", "Real"),
        ("FAKE", "Fake"),
    ]

    user = models.ForeignKey(
        AnonymousUser,
        on_delete=models.CASCADE,
        related_name="checks",
    )
    title = models.TextField()
    text = models.TextField()
    news_source = models.ForeignKey(
        NewsSource,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="checks",
    )
    label = models.CharField(max_length=4, choices=LABEL_CHOICES)
    confidence = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "news_checks"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.label} ({self.confidence:.0%}) — {self.title[:60]}"
